# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 642ea40e8533a20fc3c8e893bd3eb47de4d2d9548981a7961ffc1f4f2e66a75af503b9ba2a762dd4dde3260bad733b13293cdc8b591aff8d120176705ccad388

test:
  secret_key_base: ee9a87771d18b33d57d6a5972d433ccc3a68413da88cace1e300d50f302c2e3fced6b0f72a0886e9f7ea41b6c9622b1883a589c6ddca466ba1586bcf0d16e971

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
